### ISSUE TITLE
controller not working in exercicePDO

### ISSUE THREAD

**Issue by MathisHPCPT** [JuMANocta/B2-SQLPHP_2021#1]
Warning: include(controler/define.php): failed to open stream: No such file or directory in D:\MAMP\htdocs\1-sql\exercicePDO\index.php on line 23

why doesn't it work?

**Comment by JuMANocta** [comment]
La cause provient du mélange entre Français et Anglais, en Fr "contrôleur" en anglois "controller".
La modification est faites, merci Mathis.

**Comment by MathisHPCPT** [comment]
Merci !
